name: Publish

on:
  release:
    types:
      - released

permissions:
  contents: read

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Elixir
      uses: erlef/setup-beam@8aa8a857c6be0daae6e97272bb299d5b942675a4 # v1.19.0
      with:
        elixir-version: '1.15.2'
        otp-version: '26.0'
    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Publish
      run: mix hex.publish --yes
      env:
        HEX_API_KEY: ${{ secrets.HEX_KEY }}
